-- Re-key skills_library.manual_id after tricks were removed from NiikSkate_Ticks_Manual.xlsx
-- (296 rows -> 259 rows). Deleting duplicates renumbered Excel column A, so all but
-- a couple of tricks now sit at a different #. skills_library upserts on manual_id,
-- so syncing without re-keying first would rewrite rows in place and silently
-- re-point every skater's completed tricks and trick bag at the wrong trick.
--
-- RUN THIS BEFORE the next "Sincronizar Excel".
--
-- Tricks are matched by identity (name + area + structure), not by position:
--   256 moved to a new #, keeping their UUID and all skater progress
--     5 duplicate row(s) folded into the surviving copy, progress carried over
--    35 dropped from the sheet, deactivated rather than deleted so no FK is orphaned
--     3 genuinely new, left for the sync to insert
--
-- Generated by scripts/rekey-trick-library.mjs. Re-runnable: it no-ops once applied.
--
-- One DO block on purpose: the Supabase SQL editor does not keep temp tables alive
-- between statements, and a single statement either applies whole or rolls back.

DO $$
DECLARE
  -- Tricks that stay, listed old # -> new #. The three arrays are parallel.
  v_old INTEGER[] := ARRAY[
      1,   2,   4,   5,   6,   7,   8,   9,  11,  12,  13,  14,  15,  16,  17,  18,
     20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
     36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
     52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
     68,  69,  70,  71,  72,  73,  74,  75,  77,  78,  79,  81,  82,  83,  84,  85,
     86,  87,  88,  90,  91,  93,  94,  95,  96,  97,  98, 100, 101, 102, 104, 108,
    109, 110, 111, 112, 113, 115, 117, 119, 120, 121, 123, 124, 127, 128, 133, 134,
    135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
    151, 152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 167,
    168, 169, 173, 174, 178, 179, 180, 182, 183, 184, 185, 186, 187, 188, 189, 190,
    191, 192, 194, 195, 198, 199, 200, 201, 202, 203, 204, 205, 207, 209, 210, 211,
    212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 225, 226, 227, 228, 229,
    230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245,
    246, 247, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
    265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280,
    281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296
  ];
  v_new INTEGER[] := ARRAY[
      1,   2,   3,   4,   5,   6,   7,   8,  10,  11,  12,  13,  14,  15,  16,  17,
     18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
     34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,
     50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
     66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,
     82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
     98,  99, 100, 101, 102, 103, 105, 107, 108, 109, 110, 111, 112, 113, 114, 115,
    116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
    132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 174, 144, 145, 146,
    147, 176, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
    162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 175, 177, 178, 179,
    180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
    196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211,
    212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227,
    228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243,
    244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259
  ];
  v_name TEXT[] := ARRAY[
    '360 tabla sin llantas',                                         -- #1 -> #1
    'Reloj',                                                         -- #2 -> #2
    'Carrera de obstaculos',                                         -- #4 -> #3
    'Carrera de velocidad',                                          -- #5 -> #4
    'Escalera',                                                      -- #6 -> #5
    'Penguins and Monster walks',                                    -- #7 -> #6
    'Principiantes Course #1',                                       -- #8 -> #7
    'Trabajo en equipo',                                             -- #9 -> #8
    'Drill 1: Empujarse > subir botador > bajar de fakie',           -- #11 -> #10
    'Drill 2: Tic toc > subir botador > kick turn',                  -- #12 -> #11
    'Drill 3: Frenar > Tail scratch (stop)',                         -- #13 -> #12
    'Drill 4: Carving > Caveman > Ghostride > Tic tacs',             -- #14 -> #13
    'Equilibrio con un pie en movimiento de skate',                  -- #15 -> #14
    'Salto de tabla. Poner tablas en el piso y saltarlas. Subir y bajar botador, regresar la tabla a su lugar.', -- #16 -> #15
    'Step up',                                                       -- #17 -> #16
    'Strong Push',                                                   -- #18 -> #17
    'Basic board control and safety',                                -- #20 -> #18
    'Stance Identification',                                         -- #21 -> #19
    'Mounting Board Safely',                                         -- #22 -> #20
    'Dismounting Board Safely',                                      -- #23 -> #21
    'Pushing',                                                       -- #24 -> #22
    'regular',                                                       -- #25 -> #23
    'Foot Brake Stop',                                               -- #26 -> #24
    'Tic-Tac',                                                       -- #27 -> #25
    'Basic Kick Turn',                                               -- #28 -> #26
    'Riding on Flat Surface',                                        -- #29 -> #27
    'Riding Over Cracks',                                            -- #30 -> #28
    'Controlled Speed on Sidewalk',                                  -- #31 -> #29
    'Walking with Board',                                            -- #32 -> #30
    'Standing on Board',                                             -- #33 -> #31
    'stationary',                                                    -- #34 -> #32
    'Gentle Slope Roll',                                             -- #35 -> #33
    'Skatepak Etiquette',                                            -- #36 -> #34
    'Bowl Safety Awareness',                                         -- #37 -> #35
    'Watching Others',                                               -- #38 -> #36
    'Mini Ramp Safety Awareness',                                    -- #39 -> #37
    'Standing on Board on Flat Bottom',                              -- #40 -> #38
    'Ramp Observation',                                              -- #41 -> #39
    'Vert Ramp Awareness',                                           -- #42 -> #40
    'Vert Safety Rules',                                             -- #43 -> #41
    'Developing balance and basic movements',                        -- #44 -> #42
    'Manual - nose',                                                 -- #45 -> #43
    'Manual - tail',                                                 -- #46 -> #44
    'Riding Switch',                                                 -- #47 -> #45
    'Carving',                                                       -- #48 -> #46
    'Speed Control - carving',                                       -- #49 -> #47
    'Quick Stop - powerslide intro',                                 -- #50 -> #48
    'Riding Over Small Objects',                                     -- #51 -> #49
    'Curb Ride Up',                                                  -- #52 -> #50
    'Curb Ride Down',                                                -- #53 -> #51
    'Pumping Basics',                                                -- #54 -> #52
    'Bank Roll-In',                                                  -- #55 -> #53
    'Bank Roll-Out',                                                 -- #56 -> #54
    'Gentle Ramp Descent',                                           -- #57 -> #55
    'Bowl Wall Riding - low',                                        -- #58 -> #56
    'Carving in Shallow Bowl',                                       -- #59 -> #57
    'Rolling on Flat Bottom',                                        -- #60 -> #58
    'Pumping Basics',                                                -- #61 -> #59
    'Riding Up Transition',                                          -- #62 -> #60
    'Kick Turn on',                                                  -- #63 -> #61
    'Vert Ramp Orientation',                                         -- #64 -> #62
    'Knee Slide Bail Practice',                                      -- #65 -> #63
    'Riding Low on Vert Wall',                                       -- #66 -> #64
    'Walking',                                                       -- #67 -> #65
    'Skill 1: Balance y equilibrio > Powerpush & Balance one foot',  -- #68 -> #66
    'Skill 2: Empujarse y frenar > Push & Stop',                     -- #69 -> #67
    'Skill 3: Girar > Como girar BS/FS',                             -- #70 -> #68
    'Skill 4: Bajar un escalon > Roll of a Ledge',                   -- #71 -> #69
    'Skill 5: Como caerse > How to bail',                            -- #72 -> #70
    'Pop',                                                           -- #73 -> #71
    'Pop and grab the board',                                        -- #74 -> #72
    'Carrera de impulso - solo tic tocs',                            -- #75 -> #73
    'Walk the dog - Carrera',                                        -- #77 -> #74
    'Hippy Jumps',                                                   -- #78 -> #75
    'Juego: Skate',                                                  -- #79 -> #76
    'Ghost Ride - piso',                                             -- #81 -> #77
    'Ghost Ride - cajon',                                            -- #82 -> #78
    'Bajar el cajon/banqueta',                                       -- #83 -> #79
    'Doble Ollie, despues subir y bajar rampa con slappy',           -- #84 -> #80
    'Trown down & Caveman',                                          -- #85 -> #81
    'Ollie, Lift the body, step up, hippie jumps',                   -- #86 -> #82
    'Drill #2: Jump off/on',                                         -- #87 -> #83
    'Lift the body',                                                 -- #88 -> #84
    'Slalom',                                                        -- #90 -> #85
    'Hippy Jump Avanzado',                                           -- #91 -> #86
    'Brincar del cajon a la tabla',                                  -- #93 -> #87
    'Toe taps, Single leg snakes, Toe touches and Switcheroo',       -- #94 -> #88
    'Backside pivot, front side pivot, pivot walks, backside revert, frontside revert, BS powerslide, FS powerslide', -- #95 -> #89
    'Pegar una cuerda en el piso y hacer un fakie ollie sin pop',    -- #96 -> #90
    'Step on, step off',                                             -- #97 -> #91
    'Saltar y caer en la tabla',                                     -- #98 -> #92
    'Monster Walks',                                                 -- #100 -> #93
    'Penguin steps (180 y 360)',                                     -- #101 -> #94
    'Trow Down',                                                     -- #102 -> #95
    'Nose stall',                                                    -- #104 -> #96
    'Fakie 180',                                                     -- #108 -> #97
    'Caveman',                                                       -- #109 -> #98
    'Sex Change (giro 180 cuerpo)',                                  -- #110 -> #99
    '360 en piso',                                                   -- #111 -> #100
    'Fakie 360',                                                     -- #112 -> #101
    'Fakie Ollie',                                                   -- #113 -> #102
    'Confianza en el Bowl',                                          -- #115 -> #103
    'Linea en bowl',                                                 -- #117 -> #105
    'Early grabs en piso',                                           -- #119 -> #107
    'Rock to fakie - fakie a rock',                                  -- #120 -> #108
    'Pump (impulso y momentum)',                                     -- #121 -> #109
    'Carving Frontside',                                             -- #123 -> #110
    'Drop-in: Bank',                                                 -- #124 -> #111
    'Roll in',                                                       -- #127 -> #112
    'Early grabs',                                                   -- #128 -> #113
    'Ollie',                                                         -- #133 -> #114
    'Shuvit',                                                        -- #134 -> #115
    'No Comply',                                                     -- #135 -> #116
    'Boneless',                                                      -- #136 -> #117
    'Ollie Up Curb',                                                 -- #137 -> #118
    'Ollie Down Curb',                                               -- #138 -> #119
    'Powerslide',                                                    -- #139 -> #120
    'Drop-In',                                                       -- #140 -> #121
    'Fakie Roll Back',                                               -- #141 -> #122
    'Kick Turn on Ramp',                                             -- #142 -> #123
    'Rock to Fakie',                                                 -- #143 -> #124
    'Pumping in',                                                    -- #144 -> #125
    'Frontside Carve',                                               -- #145 -> #126
    'Backside Carve',                                                -- #146 -> #127
    'Drop-In',                                                       -- #147 -> #128
    'Fakie Roll Back',                                               -- #148 -> #129
    'Rock to Fakie',                                                 -- #149 -> #130
    'Pumping Full Transition',                                       -- #150 -> #131
    'Drop-In',                                                       -- #151 -> #132
    'Pumping on',                                                    -- #152 -> #133
    'Kick Turn on',                                                  -- #153 -> #134
    'FS 180',                                                        -- #154 -> #135
    'Varial Kickflip',                                               -- #155 -> #136
    'BS 180',                                                        -- #156 -> #137
    'Caballerial',                                                   -- #157 -> #138
    'Half Cab',                                                      -- #158 -> #139
    'Roll-in to fakie',                                              -- #160 -> #140
    'Fakie roll-in',                                                 -- #161 -> #141
    'Boardslide',                                                    -- #162 -> #142
    'Tail stall',                                                    -- #163 -> #143
    'Nose slide',                                                    -- #164 -> #174
    'Transfer - bajo',                                               -- #165 -> #144
    'Fakie 360',                                                     -- #166 -> #145
    'Spine - rock to rock',                                          -- #167 -> #146
    'Slash',                                                         -- #168 -> #147
    'Axle stall',                                                    -- #169 -> #176
    'Half Cab Rock to Fakie',                                        -- #173 -> #148
    'Pop rock',                                                      -- #174 -> #149
    'Fakie Tail stall',                                              -- #178 -> #150
    'Fakie Tail Nose Grab',                                          -- #179 -> #151
    'One Foot Tail',                                                 -- #180 -> #152
    'Feeble stall',                                                  -- #182 -> #153
    'Ollie to rock',                                                 -- #183 -> #154
    'Roll-in 50/50',                                                 -- #184 -> #155
    'Fakie 360 Kick turn',                                           -- #185 -> #156
    '360 Rock',                                                      -- #186 -> #157
    'Nollie Pop Rock',                                               -- #187 -> #158
    'Ollie to Fakie',                                                -- #188 -> #159
    'Early Grab to Fakie',                                           -- #189 -> #160
    'Fakie Tail Stall Madonna',                                      -- #190 -> #161
    'Fakie 360 turn',                                                -- #191 -> #162
    'Fakie Smith stall',                                             -- #192 -> #163
    'FS Tail stall',                                                 -- #194 -> #164
    'BS Tail stall',                                                 -- #195 -> #165
    'FS 5-0 grind',                                                  -- #198 -> #166
    'Nose stall Revert',                                             -- #199 -> #167
    'Boardslide en coping',                                          -- #200 -> #168
    'Kickflip',                                                      -- #201 -> #169
    'Heelflip',                                                      -- #202 -> #170
    'Pop Shuvit',                                                    -- #203 -> #171
    'Frontside 180',                                                 -- #204 -> #172
    '50-50 Grind',                                                   -- #205 -> #173
    'Tail Slide',                                                    -- #207 -> #175
    'Rock and Roll',                                                 -- #209 -> #177
    '50-50 On',                                                      -- #210 -> #178
    'Disaster',                                                      -- #211 -> #179
    'Frontside Grind',                                               -- #212 -> #180
    'Backside Grind',                                                -- #213 -> #181
    'Tail Stall',                                                    -- #214 -> #182
    'Axle Stall',                                                    -- #215 -> #183
    'Tail Stall',                                                    -- #216 -> #184
    '50-50 On',                                                      -- #217 -> #185
    'Rock and Roll',                                                 -- #218 -> #186
    'Axle Stall',                                                    -- #219 -> #187
    'Rock to Fakie',                                                 -- #220 -> #188
    'Tail Stall',                                                    -- #221 -> #189
    'Fakie Rock',                                                    -- #222 -> #190
    'Backside',                                                      -- #225 -> #191
    'Varial',                                                        -- #226 -> #192
    'Boardslide',                                                    -- #227 -> #193
    'Lipslide',                                                      -- #228 -> #194
    '5-O',                                                           -- #229 -> #195
    'Crooked',                                                       -- #230 -> #196
    'Blunt',                                                         -- #231 -> #197
    'Feeble',                                                        -- #232 -> #198
    'Smith',                                                         -- #233 -> #199
    'Pivot',                                                         -- #234 -> #200
    'Frontside',                                                     -- #235 -> #201
    'Backside',                                                      -- #236 -> #202
    'Layback',                                                       -- #237 -> #203
    'Blunt to Fakie',                                                -- #238 -> #204
    'Disaster',                                                      -- #239 -> #205
    'Feeble Stall',                                                  -- #240 -> #206
    'Smith Stall',                                                   -- #241 -> #207
    'Pivot Fakie',                                                   -- #242 -> #208
    'Frontside Air',                                                 -- #243 -> #209
    'Backside Air',                                                  -- #244 -> #210
    'Indy Grab',                                                     -- #245 -> #211
    'Method Air',                                                    -- #246 -> #212
    'Mute Grab',                                                     -- #247 -> #213
    'Blunt 180',                                                     -- #251 -> #214
    '360 Flip',                                                      -- #252 -> #215
    'Hardflip',                                                      -- #253 -> #216
    'Inward Heelflip',                                               -- #254 -> #217
    'Nollie Kickflip',                                               -- #255 -> #218
    'Feeble Grind',                                                  -- #256 -> #219
    'Smith Grind',                                                   -- #257 -> #220
    'Nosegrind',                                                     -- #258 -> #221
    'Hurricane Grind',                                               -- #259 -> #222
    'Air to Fakie',                                                  -- #260 -> #223
    'Melon Grab',                                                    -- #261 -> #224
    'Stalefish',                                                     -- #262 -> #225
    'Mute Air',                                                      -- #263 -> #226
    'Frontside Ollie',                                               -- #264 -> #227
    'Backside Ollie',                                                -- #265 -> #228
    'Air to Fakie',                                                  -- #266 -> #229
    'Backside Ollie',                                                -- #267 -> #230
    'Frontside Ollie',                                               -- #268 -> #231
    'Nosegrind Stall',                                               -- #269 -> #232
    'Lipslide',                                                      -- #270 -> #233
    'Stalefish Air',                                                 -- #271 -> #234
    'Melon Grab',                                                    -- #272 -> #235
    'Lien Air',                                                      -- #273 -> #236
    '540 Air',                                                       -- #274 -> #237
    'Laser Flip',                                                    -- #275 -> #238
    'Impossible',                                                    -- #276 -> #239
    '360 Shuvit',                                                    -- #277 -> #240
    'Switch Kickflip',                                               -- #278 -> #241
    'Overcrook',                                                     -- #279 -> #242
    'Noseblunt',                                                     -- #280 -> #243
    'Tailslide Pop Out',                                             -- #281 -> #244
    'Boardslide 180 Out',                                            -- #282 -> #245
    '540 Air',                                                       -- #283 -> #246
    'Frontside Invert',                                              -- #284 -> #247
    'Handplant',                                                     -- #285 -> #248
    'Frontside Invert',                                              -- #286 -> #249
    'Miller Flip',                                                   -- #287 -> #250
    'Eggplant',                                                      -- #288 -> #251
    '540 Air',                                                       -- #289 -> #252
    'Frontside Invert',                                              -- #290 -> #253
    'Kickflip to Fakie',                                             -- #291 -> #254
    'Handplant',                                                     -- #292 -> #255
    'McTwist',                                                       -- #293 -> #256
    'Frontside Invert',                                              -- #294 -> #257
    'Handplant',                                                     -- #295 -> #258
    'Gay Twist'                                                      -- #296 -> #259
  ];

  -- Duplicate rows folded into the copy that survived.
  v_lose INTEGER[] := ARRAY[92, 206, 208, 223, 224];
  v_win  INTEGER[] := ARRAY[79, 164, 169, 201, 202];

  -- Dropped from the sheet entirely.
  v_retire INTEGER[] := ARRAY[
      3,  10,  19,  76,  80,  89,  99, 103, 105, 106, 107, 114, 116, 118, 122, 125,
    126, 129, 130, 131, 132, 159, 170, 171, 172, 175, 176, 177, 181, 193, 196, 197,
    248, 249, 250
  ];

  v_pre      INTEGER;
  v_post     INTEGER;
  v_mismatch TEXT;
  v_moved    INTEGER;
  v_merged   INTEGER;
  v_retired  INTEGER;
BEGIN
  IF array_length(v_old, 1) <> 256
     OR array_length(v_new, 1) <> 256
     OR array_length(v_name, 1) <> 256 THEN
    RAISE EXCEPTION 'Mapping arrays are not all 256 long; the migration file is corrupt.';
  END IF;

  -- Which layout is the library in? Ask the tricks themselves rather than
  -- trusting a row count, so hand-added tricks above the manual do not matter.
  SELECT COUNT(*) INTO v_pre
  FROM generate_subscripts(v_old, 1) AS g(i)
  JOIN skills_library s ON s.manual_id = v_old[g.i]
  WHERE lower(btrim(s.name)) = lower(btrim(v_name[g.i]));

  SELECT COUNT(*) INTO v_post
  FROM generate_subscripts(v_old, 1) AS g(i)
  JOIN skills_library s ON s.manual_id = v_new[g.i]
  WHERE lower(btrim(s.name)) = lower(btrim(v_name[g.i]));

  IF v_post = 256 AND v_pre < 256 THEN
    RAISE NOTICE 'Library is already re-keyed. Skipping.';
    RETURN;
  END IF;

  IF v_pre <> 256 THEN
    RAISE EXCEPTION
      'Library is in neither the expected before nor after state (% of 256 tricks sit at their old #, % at their new #). Re-generate the mapping against the live library.',
      v_pre, v_post;
  END IF;

  -- Spell out any drift before touching anything.
  SELECT string_agg(format('#%s expected "%s" but found "%s"', v_old[g.i], v_name[g.i], s.name), '; ')
  INTO v_mismatch
  FROM generate_subscripts(v_old, 1) AS g(i)
  JOIN skills_library s ON s.manual_id = v_old[g.i]
  WHERE lower(btrim(s.name)) IS DISTINCT FROM lower(btrim(v_name[g.i]));
  IF v_mismatch IS NOT NULL THEN
    RAISE EXCEPTION 'Library does not match the mapping: %', left(v_mismatch, 600);
  END IF;

  -- Fold duplicate rows into the copy that survived, so a skater who completed
  -- the duplicate keeps the credit. UNIQUE(student_id, skill_id) means the move
  -- has to skip skaters who already hold the survivor.
  UPDATE student_progress p
  SET skill_id = win.id
  FROM generate_subscripts(v_lose, 1) AS g(i)
  JOIN skills_library lose ON lose.manual_id = v_lose[g.i]
  JOIN skills_library win  ON win.manual_id  = v_win[g.i]
  WHERE p.skill_id = lose.id
    AND NOT EXISTS (SELECT 1 FROM student_progress d WHERE d.student_id = p.student_id AND d.skill_id = win.id);

  -- Whatever is left on a losing row is a skater who already had the survivor.
  DELETE FROM student_progress p
  USING skills_library lose
  WHERE lose.manual_id = ANY(v_lose) AND p.skill_id = lose.id;

  UPDATE student_skill_focus f
  SET skill_id = win.id
  FROM generate_subscripts(v_lose, 1) AS g(i)
  JOIN skills_library lose ON lose.manual_id = v_lose[g.i]
  JOIN skills_library win  ON win.manual_id  = v_win[g.i]
  WHERE f.skill_id = lose.id
    AND NOT EXISTS (SELECT 1 FROM student_skill_focus d WHERE d.student_id = f.student_id AND d.skill_id = win.id);

  DELETE FROM student_skill_focus f
  USING skills_library lose
  WHERE lose.manual_id = ANY(v_lose) AND f.skill_id = lose.id;

  -- Free the numbers held by rows that are leaving, without deleting the rows:
  -- their UUIDs are still referenced by progress, trick bags and class plans.
  UPDATE skills_library SET manual_id = NULL, is_active = false
  WHERE manual_id = ANY(v_lose);
  GET DIAGNOSTICS v_merged = ROW_COUNT;

  UPDATE skills_library SET manual_id = NULL, is_active = false
  WHERE manual_id = ANY(v_retire);
  GET DIAGNOSTICS v_retired = ROW_COUNT;

  -- Two passes through an out-of-range offset: manual_id is unique and the
  -- source and target ranges overlap, so a single UPDATE would collide.
  UPDATE skills_library s
  SET manual_id = v_new[g.i] + 1000000
  FROM generate_subscripts(v_old, 1) AS g(i)
  WHERE s.manual_id = v_old[g.i];

  UPDATE skills_library
  SET manual_id = manual_id - 1000000,
      sort_order = manual_id - 1000000,
      is_active = true
  WHERE manual_id > 1000000;
  GET DIAGNOSTICS v_moved = ROW_COUNT;

  IF v_moved <> 256 THEN
    RAISE EXCEPTION 'Expected to move 256 tricks, moved %.', v_moved;
  END IF;

  -- Every trick must now answer to its new # under its own name.
  SELECT COUNT(*) INTO v_post
  FROM generate_subscripts(v_old, 1) AS g(i)
  JOIN skills_library s ON s.manual_id = v_new[g.i]
  WHERE lower(btrim(s.name)) = lower(btrim(v_name[g.i]));
  IF v_post <> 256 THEN
    RAISE EXCEPTION 'Only % of 256 tricks landed on their new #. Rolling back.', v_post;
  END IF;

  RAISE NOTICE 'Re-keyed % tricks, merged % duplicate(s), retired %. Now run "Sincronizar Excel" to pick up the 3 new trick(s).',
    v_moved, v_merged, v_retired;
END $$;
